### ISSUE TITLE
Include more fallbacks

### ISSUE THREAD

**Issue by quentin-sommer** [joshwcomeau/react-collection-helpers#1]
Hi,

I think that `<Find>` and `<Filter>` could use the same `fallback` props as `<Every>`.

It is a common pattern to filter or to try to find an item in a collection and then handle the case where nothing has been found. This would prevent introducing boilerplate code like `res.length !== 0`

What do you think?

**Comment by quentin-sommer** [comment]
Well nevermind hadn't see this before https://joshwcomeau.github.io/react-collection-helpers/demo/dist/ !

**Comment by joshwcomeau** [comment]
Hey Quentin!

Thanks for the feedback. Yeah, I think I prefer doing it this way, it feels a little more explicit. That said, there's really no reason for `Find` and `Filter` to support the same `fallback` prop that `Every` does.

In fact, we could even add it to `<BaseCollectionHelper>`, that way it's available to all helpers. Some of them (eg. `<Sort>`) would never actually need it, but it would just be ignored in those cases.

If it interests you, I'd accept a PR moving it there :)
